### ISSUE TITLE
The highlight color of block comment and line comment should be swapped.

### ISSUE THREAD

**Issue by defmys** [protostuff/protostuff-jetbrains-plugin#18]
Hello,

I come across a bug related to highlight color. It seems the block comment uses the color of line comment and vice versa.

```java 
// ProtoSyntaxHighlighter.java: 83~88
case ProtoLexer.COMMENT:
    attrKey = LINE_COMMENT;
    break;
case ProtoLexer.LINE_COMMENT:
    attrKey = BLOCK_COMMENT;
    break;
````

![highlight_color](https://cloud.githubusercontent.com/assets/3785560/15597035/fbf82568-23fe-11e6-8bd8-dcbaecc57fa4.png)

**Comment by kshchepanovskyi** [comment]
Good catch :) Thanks, will fix soon.

**Comment by kshchepanovskyi** [comment]
Fix will be released in the next few weeks as a part of version 0.4.0.
